export const SET_LOGGEDIN_USER = "SET_LOGGEDIN_USER";
export const FETCHED_USER = "FETCHED_USER";
export const GOT_ERROR = "GOT_ERROR";
export const SET_USER_BIO = "SET_USER_BIO";
export const SET_USER_IMG = "SET_USER_IMG";
export const SET_BLOG_NAME = "SET_BLOG_NAME";
export const USER_INFO_UPDATED = "USER_INFO_UPDATED";

export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";
export const FETCHED_ALL_POSTS = "FETCHED_ALL_POSTS";
export const FETCH_USER_POSTS = "FETCH_USER_POSTS";
export const FETCHED_USER_POSTS = "FETCHED_USER_POSTS";
export const ADD_TEXT_POST = "ADD_TEXT_POST";
export const ADD_IMG_POST = "ADD_IMG_POST";
export const EDIT_POST = "EDIT_POST";
export const DELETE_POST = "DELETE_POST";

export const SET_POST_TYPE_TEXT = "SET_POST_TYPE_TEXT";
export const SET_POST_TYPE_IMG = "SET_POST_TYPE_IMG";
